DROP TABLE IF EXISTS answers CASCADE;
CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  question_id INTEGER REFERENCES questions(id),
  answer VARCHAR(255) NOT NULL,
  is_correct BOOLEAN DEFAULT false
  );

ALTER SEQUENCE answers_id_seq RESTART WITH 100;
